Legg til angiograf og operator
Rapporteket/NORIC pull request #136
Opened 2022-01-18 13:41 UTC by maraut90

- Tabell over antall angioprosedyrer pr angiograf etter måned
- Tabell over antall PCI-prosedyrer pr pci-operator etter måned
- lagt til dplyr for å bruke filter-funksjonen

2022-01-18 13:48 UTC, skkrist requested changes
Oppdatere descprition med nytt versjonsnummer + opppdater news.md filen +
dplyr::filter (legg til dplyr::)

2022-01-18 14:18 UTC, skkrist approved these changes
OK:) Du kan be Are legge denne greina i QA. Så får du testa endringen der før du merger sammen med main.

2022-01-25 13:51 UTC, skkrist requested changes
Se kommentarer i filene :)

2022-01-25 13:51 UTC, skkrist commented on R/reportProcessor.R
> +  stopifnot(report %in% c("veiledning", "local_monthly"))
Her må du ha Noric rapporteken : stent, prosedyre,aktivitet

2022-01-25 13:51 UTC, skkrist commented on R/reportProcessor.R
> +  stopifnot(report %in% c("veiledning", "local_monthly"))
*rapportene

2022-01-25 13:51 UTC, skkrist commented on R/reportProcessor.R
> +  if (report == "veiledning") {
Vi ønsker ikke ha veiledning som abonnement, dette kan fjernes

2022-01-25 13:51 UTC, skkrist commented on R/reportProcessor.R
> +  if (report == "local_monthly" & userRole == "SC") {
tror ikke du trenger helgardere deg her, dersom local_monthly er valgt, betyr det at det er SC-rolle (kun SC kan velge denne).

2022-01-25 13:51 UTC, skkrist commented on R/reportProcessor.R
> +  if (report == "local_monthly" & userRole == "SC") {
Lag 3 bolker med kode her: 
if (report == "local_monthly") --> prosedyrer
if (report == "local_monthly_stent" ->
if (report == "local_monthly_acticity"

2022-01-25 13:51 UTC, skkrist commented on inst/NORIC_local_monthly_activity.Rmd
> +AP$Year <- as.numeric(
kan vi bruke lubridate::year() osv overalt ?

2022-01-25 13:51 UTC, skkrist commented on inst/NORIC_local_monthly_activity.Rmd
> +```{r subsetting,include=FALSE, eval=TRUE}
Tror dette kan fjernes, da SQL spør etter begrenset periode allerede

2022-01-25 13:51 UTC, skkrist commented on inst/NORIC_local_monthly_activity.Rmd
> +if(AP$Sykehusnavn[1] %in% c("Feiring","Rikshospitalet")) AP <- AP[which( AP$Year >= 2015), ]
Bruke heller funksjonen noric::fjerne_tulleregistreringer.

2022-01-25 13:51 UTC, skkrist commented on inst/NORIC_local_monthly_activity.Rmd
> +
husk .data$ foran alle variabler

2022-01-25 13:51 UTC, skkrist commented on inst/shinyApps/noric/server.R
> +      paramNames = c("report", "outputType", "title", "orgId", "orgName", "userRole"),
subreports <- list( 
Prosedyrer = ..., 
Stentbruk = ...)

if(is.nasjoantl = FALSE+ user.role= SC) {
subreports <- list(subreports, 
Aktivitet) }

2022-01-25 13:51 UTC, skkrist commented on inst/shinyApps/noric/server.R
> +      paramNames = c("report", "outputType", "title", "orgId", "orgName", "userRole"),
Her angis listen over mulige abonnement . 
Default er STENT + PROSEDYRER
Dersom lokal SC blir det STENT + PROSEDYRER + AKTIVITET

2022-05-19 07:59 UTC, skkrist requested changes
Kan du oppdatere DESCRIPTION (versjon 2.6.1) og NEWS.md ?

2022-05-19 12:18 UTC, skkrist commented
Har testa i QA. Ser bra ut 😄 
2 kommentarar til..
Abonnement: Tenker SC rolle lokalt burde ha tilgang på alle 3 rapportane : Aktivitet, Stent, Prosedyrer. 
Startsida. Kunne hadd Aktivitet som punkt nr 3. 

**Månedsrapporter**
Brukere(LU/LC/SSC) ved lokale sykehus har tilgang på månedsrapporter. etc.
- Stentbruk
- Prosedyrer
- Aktivitet (kun for SC rolle)

Så kan du merge for mon del!

2022-05-19 12:19 UTC, skkrist approved these changes

2022-05-19 12:23 UTC, maraut90 commented
> 

Jeg tenkte det samme etter å ha sjekket i QA 👍 
Skal gjøre disse endringen før jeg merger ;)

2022-05-20 10:15 UTC, merged